spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: none
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/course
    username: postgres
    password: 123456
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yml